linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3

run:
  timeout: 5m
  tests: true
  working-directory: engine-go

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
