repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/golangci/golangci-lint
  rev: v1.64.8
  hooks:
    - id: golangci-lint
      args: [--path-prefix, src/engine-go]
      pass_filenames: false

